import type { Metadata } from 'next'
import Header from '@/components/ui/header'
import './globals.css'

import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <Header />
        <main className={inter.className}>
        {children}
        </main>
      </body>
    </html>
  )
}
